language: node_js
node_js:
- "7"

install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.34/hugo_0.34_Linux-64bit.tar.gz -O ../hugo.tar.gz
- tar -C .. -zxf ../hugo.tar.gz hugo

script:
- ../hugo

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "q9v5bv5QjO5OgGk+yIM3W1nLUtHbXT9XoJbtv+1sexkYw4QLWrwnHvGud/PFXbc9hsLo4m5GV3aEoGVu/ITGHLT9DLsMsCPA9iYfTLcjPvx/pnNNvedwtSn4qa+pxBoN0+JHVVVkhF2MnJAhc4dGmrN69eAZ1QOSS3g66s63dv9mXs80CDzY3Keq9ndZDjl1dBhx2dOddjXD1cq31Hb+0NCbTauF/MhrLH2V+xtU9JpmwQIwISpf3oTMBy8BaanFl5F621vgQ228Ca5BjeYwwhv8Ak/cuTH7eQ/rWMCOyJo3kjjBuKMGdxesjDduxGGyRzHo9/0w0LBAw18HLqRQWqmYI9MvCAiH7qyrhjesnKOM6iV6o3vwVDFwFBCVE6e/IPifyrsuodYvYBZXAdaIqTmIrWpHJu+TYl6kcrJGbLn0VypVrhUI9lk/C0ansutd5HT3V3Yw1HYQ9AeY04FuTtMzwfTcVv17JxFiq8N4qj8xf3ifKACmryA/MTOEBzZuQbDcLsI8B2HozbAOVtMr9D3IWQryN1vjVCKu/XzcFTp77FwaYwsnP8MTOBkpOutqLnbREhrvL7SGcy03inTNPJ+kWp3EaQpfrIZFomVvq9O+uYLR/IDGYrOmiNGZackYglQRmojhdenzL/DyVqaQRRLbFC9YmFK/81skNcKUJLg="