language: node_js
node_js:
- "7"

install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.34/hugo_0.34_Linux-64bit.tar.gz -O ../hugo.tar.gz
- tar -C .. -zxf ../hugo.tar.gz hugo

script:
- ../hugo

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: ViNy65wIqZSHqxhk6ETevPm8zN4UXEjOlxGU9R+w7zDZGTF/aJJtOXnMBwHbpjBsfBrKWiaiSG834No2R7UkolaCwXzy3oz48bnqQs3WyLWqjOvFJEg2/lXcx6F5m2SGxt6LbqFzHkvZFC7nCZwuVO7K0S6fktqMq8yurXcj3vacJuvezgnxEbj6KSbJ/XQDp1bSMEmT1j1m3/e0gvn98FW2YGDl7aSgXGnihdEYfnCJQSlJc1dMQ0eXAIjspO9GP8kpwaV/lg93IlPngogaY1OS1bTO5w/WNQqGfyVxCV05P1S9LMurTkEbBlJvBzoOZGjTunaf+/uF0HthFnNa/XdUXTjQOoZiQ00Bsxb/ddbf/+M8O6iT8dDj5NZKkS1tpRXV7nnBw2ko1FoCKedyq6tnlf56ZiJkC5hW86DLAm655L+0IXW8JBPtguLzMUM4k4SY2WQNskXneHRfphe+o8ANd7N/ZHGukcWlF6TA65arSGrRbPlzNBcsavwHghaHSWDzPrI16z3+FDsKVJwGxqwM9ITGs/9zi5bMOLpJ5KHi26r6y/XSd+DjT3nJwEVXrTKaOU+gofrOP8waKNMZQ/v6k275bSUjMpub2rRE1HMk6N6E8vcV6NNna7bAtC+3+yRIyEWOZxmBT/VmgqUqD0Wcyb2dDMa9+Ap4p3GiIQA=
