baseURL = "https://blog.bdemers.io"
languageCode = "en-us"
title = "Brian Demers"
googleAnalytics = ""
theme = "future-imperfect"
enableRobotsTXT = "true"

preserveTaxonomyNames = true
pagination.pagerSize = 5
pluralizeListTitles = false
buildFuture = true

[params]
  # Sets the meta tag description
  description          = "Personal blog of Brian Demers"
  navbarTitle          = "Brian Demers"
  viewMorePostLink     = "/blog/"

# Optional Params
  # Sets RSS icons to appear on the sidebar with the social media buttons
  rssAppearAtTop       = true
  rssAppearAtBottom    = true
  # Sets Social Media icons to appear on the sidebar
  socialAppearAtTop    = true
  socialAppearAtBottom = false
  # Sets Categories to sort by number of posts instead of alphabetical
  categoriesByCount    = true
  # set to show or to hide categories in the sidebar
  showSidebarCategories = true
  # Sets Estimated Reading Time to appear in post headers
  includeReadingTime   = true
  # Sets the Favicon and Version for the site. Default support is for
  # apple-touch-icon-precomposed.png, favicon.png, favicon.ico, and mstile.png.
  # These are stored in the favicon folder. See the following for more information:
  # https://github.com/audreyr/favicon-cheat-sheet
  loadFavicon          = false
  faviconVersion       = ""
  # Sets Social Share links to appear on posts
  socialShare          = true
  socialShareGoogleplus = false

  # options for highlight.js (version, additional languages, and theme)
  disable_highlight = false
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "css", "java"]
  highlightjsTheme = "github"

  # theme configuration
  customCSS              = ["default"]
  customJS               = ["default"]

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
[params.intro]
  header    = "Brian Demers"
  paragraph = "Father, Geek 🤓, <BR> Beekeeper 🐝, <BR> Java Champion ♨️, <a href='https://gradle.com' rel='p-org'>Developer Advocate</a> 🥑"
  about     = ""

  # This appears at the top of the sidebar above params.intro.header.
  # A width of less than 100px is recommended from a design perspective.
  [params.intro.pic]
    src       = "/img/main/logo.jpg"
    circle    = true
    width     = ""
    alt       = "Brian Demers"

[params.postAmount]
# Sets the number of recent posts to show in the sidebar. The default value is 5.
    sidebar = 5

# Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item
[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "fa fa-home"
  weight = 1

#[[menu.main]]
#  name = "About"
#  url = "/about/"
#  identifier = "fa fa-id-card-o"
#  weight = 2

#[[menu.main]]
#  name = "Blog"
#  url = "/blog/"
#  identifier = "fa fa-newspaper"
#  weight = 3

#[[menu.main]]
#  name = "Presentations"
#  url = "/presentations/"
#  identifier = "fa fa-television"
#  weight = 4

[params.social]
  github           = "bdemers"
  stackoverflow    = "6415199"
  linkedin         = "bdemers"
  slideshare       = ""
  reddit           = "bdemers" # hidden in template
  bluesky          = "bdemers.io"
  mastodon         = "mastodon.social/@bdemers"
  twitter          = "briandemers"
  email            = "bdemers@apache.org"
  bridgy           = "bdemers.io"
